/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.Error
import io.swagger.client.model.Vehiculo
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object VehculoApi {

  /**
   * Los Vehículos endpoints retornan informacion sobre un vehículo dada una placa. La respuesta incluye la marca, modelo, año de fabricación y otra información relevante al vehículo. 
   * 
   * Expected answers:
   *   code 200 : Vehiculo (Un vehículo)
   *   code 0 : Error (Unexpected error)
   * 
   * @param authorization Token para acceder a los servicios de Rimac.
   * @param placa Placa del vehículo.
   */
  def vehiculoGet(authorization: String, placa: String): ApiRequest[Vehiculo] =
    ApiRequest[Vehiculo](ApiMethods.GET, "https://rasveuswap01.azurewebsites.net/RimacChatbot/rest", "/vehiculo", "application/json")
      .withQueryParam("placa", placa)
      .withHeaderParam("Authorization", authorization)
      .withSuccessResponse[Vehiculo](200)
      .withDefaultErrorResponse[Error]
      

}

