---
swagger: "2.0"
info:
  description: "Todo va estar bien con tu API favorita."
  version: "1.0.0"
  title: "Rimac API"
host: "rasveuswap01.azurewebsites.net"
basePath: "/RimacChatbot/rest"
schemes:
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /tercero:
    get:
      tags:
      - "Tercero"
      summary: "Búsqueda de terceros"
      description: "Busca un tercero a través de un tipo y número de documento de\
        \ identidad.\n"
      parameters:
      - name: "tipodoc"
        in: "query"
        description: "Tipo de documento de identidad."
        required: false
        type: "string"
        default: "2"
      - name: "nrodoc"
        in: "query"
        description: "Número de documento de identidad."
        required: true
        type: "string"
      responses:
        200:
          description: "Tercero encontrado"
          schema:
            $ref: "#/definitions/Tercero"
        404:
          description: "Tercero no encontrado"
          schema:
            $ref: "#/definitions/Error"
  /tercero/{idetercero}/mediopago:
    get:
      tags:
      - "Tercero"
      - "Medio Pago"
      summary: "Búsqueda de medios de pago de un tercero."
      description: "Busca los medios de pago de un tercero.\n"
      parameters:
      - name: "idetercero"
        in: "path"
        description: "Identificador del tercero."
        required: true
        type: "string"
      responses:
        200:
          description: "Medios de pago encontrados"
          schema:
            $ref: "#/definitions/MedioPago"
        404:
          description: "Medios de pago no encontrados"
          schema:
            $ref: "#/definitions/Error"
  /vehiculo:
    get:
      tags:
      - "Vehículo"
      summary: "Vehículo"
      description: "Busca un vehículo a través de una placa.\n"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Token de acceso."
        required: true
        type: "string"
        default: "Beared TestNoToken"
      - name: "placa"
        in: "query"
        description: "Placa del vehículo."
        required: true
        type: "string"
      responses:
        200:
          description: "Vehículo encontrado"
          schema:
            $ref: "#/definitions/Vehiculo"
        404:
          description: "Vehículo no encontrado"
          schema:
            $ref: "#/definitions/Error"
  /acuerdo:
    post:
      tags:
      - "Acuerdo"
      summary: "Acuerdo"
      description: "Creación de un acuerdo (cotización, pólizas)\n"
      consumes:
      - "application/json"
      - "text/plain"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Token de acceso."
        required: true
        type: "string"
        default: "Beared TestNoToken"
      - in: "body"
        name: "body"
        description: "datos de la cotización."
        required: true
        schema:
          $ref: "#/definitions/Cotizacion"
      responses:
        200:
          description: "Acuerdo creado, devuelve los planes"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/PlanCotizado"
        default:
          description: "Error inesperado"
          schema:
            $ref: "#/definitions/Error"
    put:
      tags:
      - "Acuerdo"
      summary: "Acuerdo"
      description: "Actualización de un acuerdo\n"
      parameters:
      - name: "ideacuerdo"
        in: "header"
        description: "Token de acceso."
        required: true
        type: "string"
        default: "Beared TestNoToken"
      - in: "body"
        name: "body"
        description: "datos de la cotización."
        required: true
        schema:
          $ref: "#/definitions/Cotizacion"
      responses:
        200:
          description: "Acuerdo actualizado"
        404:
          description: "Acuerdo no encontraro o inválido"
  /pago:
    post:
      tags:
      - "Pago"
      description: "Creación de un pago\n"
      parameters:
      - in: "body"
        name: "body"
        description: "datos del pago."
        required: true
        schema:
          $ref: "#/definitions/Pago"
      responses:
        201:
          description: "Pago creado"
definitions:
  Cotizacion:
    type: "object"
    properties:
      ideacuerdo:
        type: "string"
      fecinivig:
        type: "string"
      ideproducto:
        type: "string"
      financimiento:
        $ref: "#/definitions/Financimiento"
      ur:
        type: "array"
        items:
          $ref: "#/definitions/UnidadRiesgo"
      participantes:
        $ref: "#/definitions/Participante"
      ordenentrada:
        $ref: "#/definitions/OrdenEntrega"
    example:
      ideacuerdo: ""
      fecinivig: "01/01/2018"
      ur:
      - ideplan: ""
        oa:
        - tipo: "vehiculo"
          ideoa: "1"
          detalle:
          - idedato: "txtnumero_de_motor"
            valor: "HR16298859B"
          - idedato: "selmarcadevehiculo"
            valor: "NISSAN"
          - idedato: "selusos_de_vehiculos"
            valor: "PARTICULAR"
          - idedato: "txtnro_pasajeros"
            valor: "5"
          - idedato: "txtfechainicionuevosoat"
            valor: "01/01/2018"
          - idedato: "selmodelodevehiculo"
            valor: "TIIDA"
          - idedato: "txtmodelo_especifico"
            valor: "TIIDA"
          - idedato: "txtnumero_de_serie"
            valor: "3N1CC1AG8BL365816"
          - idedato: "selclasedevehiculo"
            valor: "AUTOMOVIL"
          - idedato: "seltipodevehiculo"
            valor: "AUTO"
          - idedato: "selanos_de_fabricacion"
            valor: "2010"
          - idedato: "txtplaca_de_rodaje"
            valor: "A7V510"
  Financimiento:
    type: "object"
    properties:
      ideplanfin:
        type: "string"
      idpvigencia:
        type: "string"
      nrocuotas:
        type: "string"
  Participante:
    type: "object"
    properties:
      iderol:
        type: "string"
      idetercero:
        type: "string"
      prc:
        type: "string"
      tipo:
        type: "string"
      idptiprelter:
        type: "string"
      tlfcontacto:
        type: "string"
      emailcontacto:
        type: "string"
      formacobro:
        $ref: "#/definitions/FormaCobro"
  FormaCobro:
    type: "object"
    properties:
      ideformacobro:
        type: "string"
  OrdenEntrega:
    type: "object"
    properties:
      fecha:
        type: "string"
      hora:
        type: "string"
      dschora:
        type: "string"
      dircontacto:
        type: "string"
      dircontactocorreo:
        type: "string"
      dscdistrito:
        type: "string"
  UnidadRiesgo:
    type: "object"
    properties:
      numero:
        type: "string"
      ideplan:
        type: "string"
      oa:
        type: "array"
        items:
          $ref: "#/definitions/ObjectoAsegurado"
  ObjectoAsegurado:
    type: "object"
    properties:
      numero:
        type: "string"
      tipo:
        type: "string"
      ideoa:
        type: "string"
      detalle:
        type: "array"
        items:
          $ref: "#/definitions/DatoParticular"
  DatoParticular:
    type: "object"
    properties:
      idevalor:
        type: "string"
      valor:
        type: "string"
  PlanCotizado:
    type: "object"
    properties:
      primaneta:
        type: "string"
      dscplan:
        type: "string"
      ideplan:
        type: "string"
      primabruta:
        type: "string"
      simbolomoneda:
        type: "string"
      prima:
        type: "string"
  Vehiculo:
    type: "object"
    properties:
      res:
        type: "string"
        description: "Resultado de la búsqueda."
      VEHICULO_SUNARP:
        $ref: "#/definitions/Vehiculo_VEHICULO_SUNARP"
  Tercero:
    type: "object"
    properties:
      codexterno:
        type: "string"
      correo:
        type: "string"
      direccion:
        type: "string"
      dscidpgenero:
        type: "string"
      edad:
        type: "string"
      estadocivil:
        type: "string"
      fecnacimiento:
        type: "string"
      idetercero:
        type: "string"
      idpgenero:
        type: "string"
      idptipodocumento:
        type: "string"
      idptipotercero:
        type: "string"
      indexrow:
        type: "string"
      nombre:
        type: "string"
      numerodoc:
        type: "string"
      stster:
        type: "string"
  MedioPago:
    type: "object"
    properties:
      idetercero:
        type: "string"
      idetarjeta:
        type: "string"
      numero:
        type: "string"
      operador:
        type: "string"
  Pago:
    type: "object"
    properties:
      idefactura:
        type: "string"
      monto:
        type: "string"
      codmoneda:
        type: "string"
      token:
        type: "string"
      fecha:
        type: "string"
      email:
        type: "string"
    example:
      idefactura: "99999999"
      monto: "10000"
      codmoneda: "PEN"
      token: "crd_test_kSbdVntf0Wwz4NIG"
      fecha: "01/12/2017"
      email: "richard@piedpiper.com"
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
    example:
      code: 404
      message: "No encontrado"
  Vehiculo_VEHICULO_SUNARP:
    properties:
      gpsRequerido:
        type: "boolean"
      anioFabricacion:
        type: "string"
      clase:
        type: "string"
      codClaseRimac:
        type: "string"
      codGrupoRimac:
        type: "string"
      codMarcaRimac:
        type: "string"
      codModeloRimac:
        type: "string"
      descClaseRimac:
        type: "string"
      descGrupoRimac:
        type: "string"
      descMarcaRimac:
        type: "string"
      descModeloRimac:
        type: "string"
      ind4X4:
        type: "string"
      indClasico:
        type: "string"
      indPractimovil:
        type: "string"
      indPremier:
        type: "string"
      marca:
        type: "string"
      modelo:
        type: "string"
      nroMotor:
        type: "string"
      nroSerie:
        type: "string"
      otraObservacion:
        type: "string"
      placaVigente:
        type: "string"
      valorComercial:
        type: "integer"
      valorNuevo:
        type: "integer"
      tipoAltoRiesgo:
        type: "string"
      codTipoRimac:
        type: "string"
      descTipoRimac:
        type: "string"
      indChinoHindu:
        type: "string"
x-azure-api-id: "RimacAPI"
