/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class PlanCotizado (
  primaneta: Option[String],
  dscplan: Option[String],
  ideplan: Option[String],
  primabruta: Option[String],
  simbolomoneda: Option[String],
  prima: Option[String]
) extends ApiModel


