/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Vehiculo_VEHICULO_SUNARP (
  tipoAltoRiesgo: Option[String],
  descTipoRimac: Option[String],
  codGrupoRimac: Option[String],
  valorComercial: Option[Int],
  clase: Option[String],
  marca: Option[String],
  indPractimovil: Option[String],
  descModeloRimac: Option[String],
  placaVigente: Option[String],
  otraObservacion: Option[String],
  anioFabricacion: Option[String],
  codMarcaRimac: Option[String],
  nroSerie: Option[String],
  descClaseRimac: Option[String],
  nroMotor: Option[String],
  codClaseRimac: Option[String],
  descGrupoRimac: Option[String],
  descMarcaRimac: Option[String],
  indClasico: Option[String],
  modelo: Option[String],
  indChinoHindu: Option[String],
  gpsRequerido: Option[Boolean],
  valorNuevo: Option[Int],
  codModeloRimac: Option[String],
  indPremier: Option[String],
  ind4X4: Option[String],
  codTipoRimac: Option[String]
) extends ApiModel


